<?php

return [
    'base_url' => env('UAZAPI_BASE_URL', 'https://funnelchat.uazapi.com'),
    'admin_token' => env('UAZAPI_ADMIN_TOKEN'),
    'timeout' => env('UAZAPI_TIMEOUT', 120),
    'endpoints' => [
        'qr_code' => '/instance/connect',
        'status' => '/instance/status',
        'connect' => '/instance/connect',
        'disconnect' => '/instance/disconnect',
        'send_message' => '/send/text',
        'send_image' => '/send/media',
        'send_video' => '/send/media',
        'send_audio' => '/send/media',
        'send_document' => '/send/media',
        'send_location' => '/send/location',
        'send_contact' => '/send/contact',
        'send_buttons' => '/send/menu',
        'send_list' => '/send/menu',
        'send_poll' => '/send/menu',
        'send_link' => '/send/text',
        'groups' => '/group/list',
        'group' => '/group/info',
        'create_group' => '/group/create',
        'update_group_name' => '/group/updateName',
        'update_group_description' => '/group/updateDescription',
        'update_group_announce' => '/group/updateAnnounce',
        'update_group_locked' => '/group/updateLocked',
        'update_group_photo' => '/group/updateImage',
        'leave_group' => '/group/leave',
        'contacts' => '/contacts',
        'contact' => '/contact/add',
        'chats' => '/chat/find',
        'delete_chat' => '/chat/delete',
        'delete_message' => '/message/delete',
        'create_community' => '/community/create',
        'communities' => '/group/list',
        'community_metadata' => '/group/info',
        'group_invitation' => '/group/inviteInfo',
    ],
    'status_messages' => [
        'disconnected' => 'disconnected',
        'connecting' => 'connecting',
        'connected' => 'connected',
    ],
    'errors' => [
        'connection_error' => 'Failed to connect to UAZ API',
        'invalid_token' => 'Invalid token or expired',
        'instance_not_found' => 'Instance not found',
        'rate_limit' => 'Rate limit exceeded',
    ],
];

